# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3485ddbdb350bf72dfe882bbb60def9982982f0659cf786f109efe0f7f986a0cd4efdc345aa3ee7ffc26c5f6ddd91000dd8d301ba961d23c6f76f72ec53b9ad7

test:
  secret_key_base: d1985d7979c85e61ec1179ee6f3a65facfd439d15ff8395329aa5688bb7c9e7cf8543fe413b9d8001ff32d143c5c6563e4e4a86339e127acf392fbb8f6950021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
